### PR TITLE
Mixin Refinements

### LINKED ISSUE #631: [BUG] Mixin crashes JW Lua
**Describe the bug**
Creating a `FCMCustomWindow` with JW Lua crashes Finale.

**To Reproduce**
Run this code:
```lua
local mixin = require("library.mixin")
local dlg = mixin.FCMCustomWindow()
```

Finale crashes on the 2nd line.

**Desktop (please complete the following information):**
 - OS: macOS 12.7.1
 - I tried both Finale 27.4 and 25.5
 - JW Lua Version 0.54
 - Script Name: mixin.lua

**Additional context**
I tried creating an FCMString (i.e., `mixin.FCMString()`) and it did not crash Finale and appeared to work. This appears to be a problem specific to `FCMCustomWindow` and its subclasses.

I am not certain how much effort is worth expending to support JW Lua, but we have made an effort for the `mixin` library to support it up till now.

@ThistleSifter

### LINKED ISSUE #636: [BUG] Mixin FCMCustomLuaWindow does not support `FCCtrlRadioButtonGroup`
`FCCtrlRadioButtonGroup` is not an `FCControl`. It is a group of controls that the PDK Framework manages as a single control, but each member of the group has its own control id. It behaves like an `FCCollection` without actually being one. Still, it can be iterated with `each`.

This looks like a somewhat straightforward modification to the `create_control` function in `FCCustomLuaWindow.lua`, but there are a couple of issues:

- There will only be one name for the button group, and I am not quite sure how to handle that.
- I am not sure the ramifications of adding multple control id's for a single group.

Here is the [documentation page](https://pdk.finalelua.com/class_f_c_ctrl_radio_button_group.html) for `FCCtrlRadioButtonGroup`.

@ThistleSifter

### LINKED ISSUE #638: [BUG] Mixin FCMCustomLuaWindow does not support `FCCtrlComboBox`
I was able to add "ComboBox" in the `create_control` loop in `FCMCustomLuaWindow.lua`, which allows the dialog to open. But re-displaying it causes the script to crash. It needs a `FCMCtrlCombobox.lua`.

In the context of the PDK Framework, `FCCtrlComboBox` is a combined popup menu and edit text box. It in fact is a subclass of `FCCtrlEdit`. So we can think of it conceptually as an edit text box with a popup button attached. `FCMCtrlComboBox.lua` is going to need everything in `FCMCtrlEdit.lua` and `FCMCtrlPopup.lua` combined. My questions are:

- Is there a way directly to reuse those?
- Does the fact that the PDK Framework `FCCtrlComboBox` actually inherits from `FCCtrlEdit` have any bearing on this?

For reference, on Windows both `FCCtrlPopup` and `FCCtrlComboBox` are combo boxes. (The former is read-only.) On macOS, they are unrelated controls that bear a superficial resemblance to each other. (`NSPopUpButton` vs. `NSComboBox`.)

@ThistleSifter

### PR DESCRIPTION
**Pull request by rpatters1**
- delint repo (including a couple minor mixin issues)
- add minimal support for `FCCtrlComboBox`.
- add support for `FCCtrlRadioButtonGroup`.
- fix issue causing JW Lua crash.

The JW Lua crash was due to adding controls that did not exist in JW Lua. It seems that indexing the `__class` table of a class with an invalid index crashes JW Lua. This code uses a sequential search of the table instead (when it is for JW Lua). I searched the repo, but I could not find other examples of indexing `__class` when there is the potential of indexing with an invalid index. A similar risk probably exists for `__static`, `__propget`, and `__propset` as well.

In addition to @ThistleSifter, I am adding @jwink75 as a reviewer as well. I made delinting changes to `harp_pedal_wizard.lua` and I would like JWink75 to review them. They are minimal, but the script appears to be working correctly. One of the issues revealed a problem in my current dev branch of RGP Lua, so I am grateful to it.

Resolves #638
Resolves #636 
Resolves #631

### CODE REVIEW

**Comment by jwink75** [comment]
Well, I think the changes you made to fix the linting errors seem fine... But in testing them I found another little bug that I hadn't noticed before, and there's a feature refinement that has been requested that I don't think it would be too much trouble to add. I'll try to finish up work on that ASAP!

-Jake

On 1/15/2024 11:40:27 AM, rpatters1 ***@***.***> wrote:
* delint repo (including a couple minor mixin issues)
* add minimal support for FCCtrlComboBox.
* add support for FCCtrlRadioButtonGroup.
* fix issue causing JW Lua crash.
The JW Lua crash was due to adding controls that did not exist in JW Lua. It seems that indexing the __class table of a class with an invalid index crashes JW Lua. This code uses a sequential search of the table instead (when it is for JW Lua). I searched the repo, but I could not find other examples of indexing __class when there is the potential of indexing with an invalid index. A similar risk probably exists for __static, __propget, and __propset as well.
In addition to @ThistleSifter [https://github.com/ThistleSifter], I am adding @jwink75 [https://github.com/jwink75] as a reviewer as well. I made delinting changes to harp_pedal_wizard.lua and I would like JWink75 to review them. They are minimal, but the script appears to be working correctly. One of the issues revealed a problem in my current dev branch of RGP Lua, so I am grateful to it.
Resolves #638 [https://github.com/finale-lua/lua-scripts/issues/638]
Resolves #636 [https://github.com/finale-lua/lua-scripts/issues/636]
Resolves #631 [https://github.com/finale-lua/lua-scripts/issues/631]
You can view, comment on, or merge this pull request online at:
  https://github.com/finale-lua/lua-scripts/pull/640 [https://github.com/finale-lua/lua-scripts/pull/640]
Commit Summary
* b4e1ab1 [https://github.com/finale-lua/lua-scripts/pull/640/commits/b4e1ab16146e01431d21d32a40ed68eda2c288d1] delint repo
* 2ed3ef9 [https://github.com/finale-lua/lua-scripts/pull/640/commits/2ed3ef97514ee1c970ddb2b461e62915ddfcb6fb] update version/date
* 6a19fc4 [https://github.com/finale-lua/lua-scripts/pull/640/commits/6a19fc480f1a0ebd60f91f2f38d267217a05c688] Add mixin support for FCCtrlRadioButtonGroup
* 8636217 [https://github.com/finale-lua/lua-scripts/pull/640/commits/86362177ec91779a1f9916a5ac93da85ddacd553] fix latest JW Lua crash
File Changes
(5 files [https://github.com/finale-lua/lua-scripts/pull/640/files])
* M samples/modeless_dialog.lua [https://github.com/finale-lua/lua-scripts/pull/640/files#diff-008ef94e55ae90abbef6c73f45b6e358aaa089e5c5309d68a024ec1a3b045452] (240)
* M src/harp_pedal_wizard.lua [https://github.com/finale-lua/lua-scripts/pull/640/files#diff-c64acefda21bb3939d10e4f3bcddb8603274e793101a53cfe5027a0adce60d4d] (22)
* M src/mixin/FCMCustomWindow.lua [https://github.com/finale-lua/lua-scripts/pull/640/files#diff-c43a0cc845ae9afd2b32efad46dee0b0eb44c24bff9dd297f69e0db51d68fe84] (39)
* M src/mixin/FCXCtrlUpDown.lua [https://github.com/finale-lua/lua-scripts/pull/640/files#diff-bef941de93bc9078ef232e085137ab3bca5caf2845eb0392b852c2621cd7ae20] (2)
* M src/playback_selected_staves.lua [https://github.com/finale-lua/lua-scripts/pull/640/files#diff-55059375e707f5b5727887deb7506899c014a6a69144929db03047b33c93c903] (2)
Patch Links:
* https://github.com/finale-lua/lua-scripts/pull/640.patch [https://github.com/finale-lua/lua-scripts/pull/640.patch]
* https://github.com/finale-lua/lua-scripts/pull/640.diff [https://github.com/finale-lua/lua-scripts/pull/640.diff]

File: src/mixin/FCMCustomWindow.lua [hunk 1]
```diff
@@ -326,12 +337,24 @@ Override Changes:
...
     [2] = {"Button", "Checkbox", "CloseButton", "DataList", "Edit", "TextEditor",
-        "ListBox", "Popup", "Slider", "Static", "Switcher", "Tree", "UpDown",
+        "ListBox", "Popup", "Slider", "Static", "Switcher", "Tree", "UpDown", "ComboBox",
     },
-    [3] = {"HorizontalLine", "VerticalLine",},
+    [3] = {"HorizontalLine", "VerticalLine", "RadioButtonGroup"},
 }) do
     for _, control_type in pairs(ctrl_types) do
-        if not finale.FCCustomWindow.__class["Create" .. control_type] then
+        local got1 = false
```
Comment (ThistleSifter) [inline src/mixin/FCMCustomWindow.lua:345]: For readability, `type_exists`? Sounds less like a nice afternoon down the river on a boat with a line and a gentle breeze...

Comment (rpatters1) [reply src/mixin/FCMCustomWindow.lua]: Fixed

**Comment by ThistleSifter** [comment]
As it stands, the radio button group can be named but the individual radio buttons cannot. Since names are immutable and defined at time of creation, I'd propose the following signature for the mixin `CreateRadioButtonGroup` method: `function(number x, number y, number|table-of-strings no_of_items [, string name])`
 
For example, all of the following would create a radio button group with 3 buttons:
```lua
-- 3 anonymous buttons
dialog:CreateRadioButtonGroup(0, 0, 3)

-- 3 named buttons
dialog:CreateRadioButtonGroup(0, 0, {"radio_a", "radio_b", "radio_c"})

-- 2 anonymous buttons, 1 named button
dialog:CreateRadioButtonGroup(0, 0, {nil, "radio_b", nil})
```

**Comment by rpatters1** [comment]
That probably needs to go into a separate method signature somehow. I like the concept, but it's a larger scope than I want to take on at the moment. Given how the `FCCtrlRadioButtonGroup` class works (conceptually like a popup menu), its naming seems more important for the base signature.

**Comment by ThistleSifter** [comment]
My proposal above doesn't impact naming the group itself. For example, this names both the radio buttons and the group:

```lua
dialog:CreateRadioButtonGroup(0, 0, {"stem_up", "stem_down", "stem_auto"}, "stem_direction")
```

I'm happy to write it up.

**Comment by rpatters1** [comment]
By all means write it up. I would recommend placing the table of control names after the group name. That keeps the call parallel to the others, and I think the group name is more important anyway.
